using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IkeMtz.NRSRx.Core.Models;

namespace IkeMtz.Samples.Models.V1
{
  // Generated by the SQL POCO Class Generator Script
  // Script is available at:
  // https://raw.githubusercontent.com/ikemtz/NRSRx/master/tools/sql-poco-class-generator.sql

  public partial class Course : CourseUpsertRequest, IIdentifiable, IAuditable
  {
    public Course()
    {
      StudentCourses = new HashSet<StudentCourse>();
      SchoolCourses = new HashSet<SchoolCourse>();
    }

    [DefaultValue(0)]
    public double? AvgScore { get; set; }
    [Required]
    [MaxLength(250)]
    public string CreatedBy { get; set; }
    [Required]
    public DateTimeOffset CreatedOnUtc { get; set; }
    [MaxLength(250)]
    public string? UpdatedBy { get; set; }
    public DateTimeOffset? UpdatedOnUtc { get; set; }
    public int? UpdateCount { get; set; }
    public virtual ICollection<StudentCourse> StudentCourses { get; }
    public virtual ICollection<SchoolCourse> SchoolCourses { get; }
  }

}
