// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.Logging.TestContextLogger.BeginScope``1(``0)~System.IDisposable")]
[assembly: SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.Swagger.SwaggerUnitTests.TestHtmlPageAsync(Microsoft.AspNetCore.TestHost.TestServer)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.Swagger.SwaggerUnitTests.TestJsonDocAsync(Microsoft.AspNetCore.TestHost.TestServer,System.Int32)~System.Threading.Tasks.Task{Microsoft.OpenApi.Models.OpenApiDocument}")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.DbContextFactory.CreateDbContextOptions``1(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)~Microsoft.EntityFrameworkCore.DbContextOptions{``0}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.CoreODataTestStartup`2.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment,Microsoft.AspNet.OData.Builder.VersionedODataModelBuilder,Microsoft.AspNetCore.Mvc.ApiExplorer.IApiVersionDescriptionProvider)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.CoreODataTestStartup`2.SetupMvcOptions(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.AspNetCore.Mvc.MvcOptions)")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.WebApi.Unit.ControllerFactory`1.Create(System.Object[])~`0")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.CoreWebApiTestStartup`1.SetupMvcOptions(Microsoft.Extensions.DependencyInjection.IServiceCollection,Microsoft.AspNetCore.Mvc.MvcOptions)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.CoreWebApiTestStartup`1.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment,Microsoft.AspNetCore.Mvc.ApiExplorer.IApiVersionDescriptionProvider)")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.TestContextRequestLoggerMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.BaseUnigrationTests.ExecuteOnContext``1(Microsoft.Extensions.DependencyInjection.IServiceCollection,System.Action{``0})")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.HttpClientExtensions.PutAsJsonAsync``1(System.Net.Http.HttpClient,System.String,``0)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.HttpClientExtensions.PostAsJsonAsync``1(System.Net.Http.HttpClient,System.String,``0)~System.Threading.Tasks.Task{System.Net.Http.HttpResponseMessage}")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.CoreTestServerExtensions.BuildSignalrConnection(Microsoft.AspNetCore.TestHost.TestServer)~Microsoft.AspNetCore.SignalR.Client.HubConnection")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.CoreTestServerExtensions.BuildSignalrConnection(Microsoft.AspNetCore.TestHost.TestServer,System.String)~Microsoft.AspNetCore.SignalR.Client.HubConnection")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:IkeMtz.NRSRx.Core.Unigration.SignalR.CoreSignalrUnigrationTestStartup`1.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
